### ISSUE TITLE
WPF project replication error

### ISSUE THREAD

**Issue by meteoric9637** [couchbaselabs/mobile-training-todo#127]
I changed SyncGatewayUrl with my couchbase server, and I made sync-gateway with this configuration file.

```
{
  "interface":":4984",
  "log": ["HTTP", "Auth"],
  "databases": {
    "todo": {
      "server": "walrus:",
      "bucket": "todo",
      "users": {
        "user1": {"password": "pass", "admin_channels": ["user1"]},
        "user2": {"password": "pass", "admin_channels": ["user2"]},
        "mod": {"password": "pass", "admin_roles": ["moderator"]},
        "admin": {"password": "pass", "admin_roles": ["admin"]},
        "todo": {"password": "pass", "admin_channels": ["todo"]}
      },
      "roles": {
        "moderator": {},
        "admin": {}
      },
      "sync": `
function(doc, oldDoc){

...
```

The server is working well.
But when I run the wpf project I'm getting below exception in HandleAccessChanged method.

```
INFO) SYNC (Replication): [17] 2017-4-25 02:31:54.703+01:00 Pusher 47e35213-06b1-44c3-89ff-a1c111b1908d successfully logged in!
INFO) SYNC (Replication): [17] 2017-4-25 02:31:54.707+01:00 Pusher 47e35213-06b1-44c3-89ff-a1c111b1908d no local checkpoint, not getting remote one
WARN) SYNC (RemoteSession): [6] 2017-4-25 02:31:56.865+01:00 Http Message failed to send, or got error response, passing to callback... http://couchbase-dev.thisisdmg.com:4984/_revs_diff, :
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Couchbase.Lite.HttpResponseException: Exception of type 'Couchbase.Lite.HttpResponseException' was thrown.
   at Couchbase.Lite.Util.TransientErrorRetryHandler.HandleTransientErrors(Task`1 request, Object state)
   at Couchbase.Lite.Util.TransientErrorRetryHandler.<ResendHandler>c__AnonStorey0.<>m__0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at Couchbase.Lite.CouchbaseLiteHttpClient.<SendAsync>c__AnonStorey2.<>m__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Couchbase.Lite.HttpResponseException: Exception of type 'Couchbase.Lite.HttpResponseException' was thrown.
   at Couchbase.Lite.Util.TransientErrorRetryHandler.HandleTransientErrors(Task`1 request, Object state)
   at Couchbase.Lite.Util.TransientErrorRetryHandler.<ResendHandler>c__AnonStorey0.<>m__0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at Couchbase.Lite.CouchbaseLiteHttpClient.<SendAsync>c__AnonStorey2.<>m__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) [HttpResponseException: StatusCode = NotFound]<---
<---

WARN) SYNC (RemoteSession): [6] 2017-4-25 02:31:56.867+01:00 	Failed content: <redacted>
```

**Comment by jamiltz** [comment]
`StatusCode = NotFound` sounds like the server isn't reachable from the device where CBLite is starting the replication. Can you access `http://couchbase-dev.thisisdmg.com:4984/_revs_diff` from the browser on that device?

**Comment by meteoric9637** [comment]
Yeah, I solved the problem, I've tried to access with wrong auth.
