### ISSUE TITLE
[react-native-android] Application not working 

### ISSUE THREAD

**Issue by ismdcf** [couchbaselabs/mobile-training-todo#152]
Application is not working on the emulator or in a real device.
![screenshot_2017-08-02-15-37-56](https://user-images.githubusercontent.com/16378404/28869024-e71a6f5a-776a-11e7-9ce6-ba425dbdfdcc.jpg)
Once I click on the error link and get the following printed on the packager console 

`ypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at launchEditor (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/util/launchEditor.js:153:29)
    at Object.handle (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/middleware/openStackFrameInEditorMiddleware.js:17:7)
    at next (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.compression [as handle] (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/compression/index.js:205:5)
    at next (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/connect/lib/proto.js:174:15)
    at IncomingMessage.<anonymous> (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/middleware/loadRawBodyMiddleware.js:20:5)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at launchEditor (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/util/launchEditor.js:153:29)
    at Object.handle (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/middleware/openStackFrameInEditorMiddleware.js:17:7)
    at next (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.compression [as handle] (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/compression/index.js:205:5)
    at next (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/connect/lib/proto.js:174:15)
    at IncomingMessage.<anonymous> (/home/ismail/Misc/training/couchbase_react_native_android_and_ios/mobile-training-todo/react-native/node_modules/react-native/local-cli/server/middleware/loadRawBodyMiddleware.js:20:5)
`

**Comment by ugendrang** [comment]
It works for me when installing the dependencies with exact versions,

  "dependencies": {
    "rc-swipeout": "1.2.0",
    "react": "15.4.1",
    "react-native": "0.39.2",
    "react-native-couchbase-lite": "0.6.0",
    "react-native-prompt": "1.0.0",
    "react-native-router-flux": "3.37.0",
    "react-native-scrollable-tab-view": "0.7.0",
    "react-native-vector-icons": "3.0.0"
  },
