### ISSUE TITLE
2.0: Android - Add conflict resolver

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/mobile-training-todo#159]

**Comment by loongsun** [comment]
hi,hideki: have you added the conflict resolver in the todo Application? i can't find it!

**Comment by rajagp** [comment]
@loongsun  Since this issue is open, I don't believe it is supported. In the meantime, this is an example of what you would have to do to implement a custom resolver
```
// Set custom conflict resolver 
// In Database configuration
config.setConflictResolver(/*Set object that implements the resolver method*/ );

// Implement the custom resolver
@Override
public ReadOnlyDocument resolve(Conflict conflict) {
      // Get revisions in conflict. Select a winner or merge changes to base
      ReadOnlyDocument mine  = conflict.getMine();
      ReadOnlyDocument theirs = conflict.getTheirs();

     // You can alternatively merge mine and theirs and return a new merged document
      return mine; 
}

```

**Comment by loongsun** [comment]
Thanks to rajagp. I will try it using your method!

**Comment by loongsun** [comment]
ConflictResolver cf=new ConflictResolver()
		{
			@Override
			public ReadOnlyDocument resolve(Conflict conflict) {

				return conflict.getMine();
			}
		};
        config.setConflictResolver(cf);

is it right?

**Comment by loongsun** [comment]
update the same item on the same time on two devices,the conflict error also happen：----------


09-12 11:13:32.109 28335-28335/com.kitchenmanage E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.kitchenmanage, PID: 28335
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.couchbase.litecore.C4Document.getSelectedRevID()' on a null object reference
                                                                       at com.couchbase.lite.CBLC4Doc.getSelectedRevID(CBLC4Doc.java:45)
                                                                       at com.couchbase.lite.ReadOnlyDocument.getRevID(ReadOnlyDocument.java:203)
                                                                       at com.couchbase.lite.ReadOnlyDocument.selectCommonAncestor(ReadOnlyDocument.java:196)
                                                                       at com.couchbase.lite.Database.resolveConflictInDocument(Database.java:751)
                                                                       at com.couchbase.lite.Replicator.documentError(Replicator.java:427)
                                                                       at com.couchbase.lite.Replicator.access$100(Replicator.java:35)
                                                                       at com.couchbase.lite.Replicator$1$2.run(Replicator.java:397)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:167)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5510)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

**Comment by hideki** [comment]
Hi @loongsun,
Thank you for reporting the bug.
There is a bug in replicating the conflicted document. We are currently investigating it.

**Comment by hideki** [comment]
Hi @loongsun ,
The problem was fixed in couchbase-lite-android repository. PR is https://github.com/couchbase/couchbase-lite-android/pull/1395.
The fix should be in next DB017 release.

**Comment by hideki** [comment]
https://github.com/couchbaselabs/mobile-training-todo/commit/7d271a47d3649b3e67c16c036bd94fd35aaf1325
