### ISSUE TITLE
Replicator is crashing in a cluster with SG accel (distributed index cluster)

### ISSUE THREAD

**Issue by hrajput89** [couchbaselabs/mobile-training-todo#170]
Setup a cluster with SG Accel and started todo 2.0 app, replicator crashed with below error

```

01/11 13:28:17: Launching todo
$ adb install-multiple -r -t /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_3.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/dep/dependencies.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_4.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_7.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_8.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_9.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_6.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_5.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_2.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_1.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/intermediates/split-apk/debug/slices/slice_0.apk /Users/hemant/couchbase/couchbase/mobile-training-todo-2.0/mobile-training-todo/android/todo/build/outputs/apk/debug/todo-debug.apk 
Split APKs installed
$ adb shell am start -n "com.couchbase.todo/com.couchbase.todo.LoginActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.couchbase.todo.test | com.couchbase.todo
Waiting for application to come online: com.couchbase.todo.test | com.couchbase.todo
Waiting for application to come online: com.couchbase.todo.test | com.couchbase.todo
Waiting for application to come online: com.couchbase.todo.test | com.couchbase.todo
Waiting for application to come online: com.couchbase.todo.test | com.couchbase.todo
Connecting to com.couchbase.todo
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/art: Debugger is active
Connected to the target VM, address: 'localhost:8733', transport: 'socket'
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1302)
I/InstantRun: starting instant run server: is main process
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.

                   [ 01-10 15:31:42.750  8581: 8581 D/         ]
                   HostConnection::get() New Host Connection established 0xd749e240, tid 8581


                   [ 01-10 15:31:42.797  8581: 8581 W/         ]
                   Process pipe failed
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
E/libEGL: load_driver(/system/lib/egl/libGLES_emulation.so): dlopen failed: library "/system/lib/egl/libGLES_emulation.so" not found
D/libEGL: loaded /system/lib/egl/libEGL_emulation.so
D/libEGL: loaded /system/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /system/lib/egl/libGLESv2_emulation.so

          [ 01-10 15:31:43.046  8581: 8601 D/         ]
          HostConnection::get() New Host Connection established 0xd749ef40, tid 8601
I/art: Do partial code cache collection, code=25KB, data=30KB
I/art: After code cache collection, code=25KB, data=30KB
I/art: Increasing code cache capacity to 128KB
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
E/EGL_emulation: tid 8601: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcb3365c0, error=EGL_BAD_MATCH
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
I/art: Do partial code cache collection, code=61KB, data=57KB
I/art: After code cache collection, code=61KB, data=57KB
I/art: Increasing code cache capacity to 256KB
I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.todo/files/hemant.cblite2/db.sqlite3
I/LiteCoreJNI: [NATIVE] C4Replicator.create()
I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.todo/files/hemant.cblite2/db.sqlite3
I/LiteCore [BLIP]: {1}--> ->blip:172.16.1.234:4985/todo/_blipsync
I/LiteCore [BLIP]: {1} Opening connection...
I/LiteCore [Actor]: Starting Scheduler<0xcb48d640> with 4 threads
I/LiteCoreJNI: [NATIVE] C4Replicator.create() repl -> 0x0xcb360c80
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCoreJNI: [NATIVE] C4Replicator.getStatus() repl -> 0xcb360c80
E/C4Socket: C4Socket.callback.open() socket -> 0xe435d588, scheme -> blip, hostname -> 172.16.1.234, port -> 4985, path -> /todo/_blipsync
E/C4Socket: optionsFleece: not null
E/Sync: Replicator[<*> blip://172.16.1.234:4985/todo/] is connecting, progress 0/0, error: null
E/C4Socket: options = {auth={username=hemant, type=Basic, password=pass}, headers={User-Agent=CouchbaseLite/2.0.0-152 (Java; Android 7.1.1; Google Pixel XL - 7.1.0 - API 25 - 1440x2560) Build/0 Commit/095ea71}}
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/LiteCoreJNI: [NATIVE] C4Replicator.getResponseHeaders() repl -> 0xcb360c80
E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=2, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
E/Sync: Replicator[<*> blip://172.16.1.234:4985/todo/] is connecting, progress 0/0, error: null
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
E/WebSocket: WebSocketListener.onOpen() response -> Response{protocol=http/1.1, code=101, message=Switching Protocols, url=http://172.16.1.234:4985/todo/_blipsync}
E/WebSocket: receivedHTTPResponse() httpStatus -> 101
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [BLIP]: {1} Connected!
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {1}--> Repl->blip:172.16.1.234:4985/todo/_blipsync
I/LiteCore [Sync]: {1} BLIP Connected
I/LiteCore [Sync]: {1} now busy
I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xcb360c80 status -> 4
E/C4Replicator: statusChangedCallback() handle -> 3409316992, status -> C4ReplicatorStatus{activityLevel=4, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
I/LiteCore [Actor]: DB->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {2}--> DB->blip:172.16.1.234:4985/todo/_blipsync
I/LiteCore [Sync]: {2} now idle
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {1} No local checkpoint 'cp-Vyc7b5+Ge2DeOSF+HcORLF0jlyA='
I/LiteCore [Actor]: Pull->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {3}--> Pull->blip:172.16.1.234:4985/todo/_blipsync
I/LiteCore [Sync]: {3} now busy
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
E/C4Socket: C4Socket.callback.write() handle -> 0xe435d588, allocatedData.length -> 58
I/LiteCore [Actor]: Push->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {4}--> Push->blip:172.16.1.234:4985/todo/_blipsync
I/LiteCore [Sync]: {4} Starting continuous push from local seq 1
I/LiteCore [Sync]: {4} Reading 200 changes since sequence 0 ...
I/LiteCore [Sync]: {4} now busy
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: Pull->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {3} Starting pull from remote seq 
I/LiteCore [Actor]: DB->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {2} Reading up to 200 local changes since #0
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: Push->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {4} Caught up, at lastSequence 0
I/LiteCore [Sync]: {4} now idle
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: Pull->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: Pull->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
E/C4Socket: C4Socket.callback.write() handle -> 0xe435d588, allocatedData.length -> 58
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
E/C4Socket: C4Socket.callback.write() handle -> 0xe435d588, allocatedData.length -> 15
E/WebSocket: WebSocketListener.onMessage() bytes -> 01020d020034303400030048545450006d697373696e67
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
E/C4Socket: C4Socket.callback.completedReceive() socket -> 0xe435d588, byteCount -> 23
I/LiteCore [Sync]: {1} No remote checkpoint
I/LiteCore [Sync]: {1} ...got remote checkpoint: [0, ''] rev=''
E/WebSocket: WebSocketListener.onMessage() bytes -> 020100
E/C4Socket: C4Socket.callback.completedReceive() socket -> 0xe435d588, byteCount -> 3
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [Actor]: Pull->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: Pull->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
E/WebSocket: WebSocketListener.onFailure() response -> null
             java.io.EOFException
                 at okio.RealBufferedSource.require(RealBufferedSource.java:60)
                 at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
                 at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
                 at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
                 at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
                 at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
                 at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                 at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                 at java.lang.Thread.run(Thread.java:761)
I/LiteCore [WS]: {1}--> blip:172.16.1.234:4985/todo/_blipsync
I/LiteCore [WS]: {1} sent 131 bytes, rcvd 26, in 0.036 sec (3643/sec, 723/sec)
I/LiteCore [Actor]: BLIP[->blip:172.16.1.234:4985/todo/_blipsync] performNextMessage
I/LiteCore [BLIP]: {1} Closed with WebSocket status 1000: 
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Sync]: {1} Connection closed with WebSocket status 1000: ""
I/LiteCore [Sync]: {1} now stopped
I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xcb360c80 status -> 0
I/LiteCore [Actor]: DB->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: Push->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [Actor]: Pull->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
I/LiteCore [BLIP]: {2}--> N8litecore4blip6BLIPIOE 0xe435d600
I/LiteCore [BLIP]: {2} ~BLIPIO: Max outbox depth was 1, avg 1.00
I/LiteCore [DB]: Closing DataFile
I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["._id"]],"ORDER_BY":[[".name"]],"WHERE":["=",[".type"],"task-list"]}
I/LiteCore [SQL]: Compiled Query: SELECT sequence, key, version, flags, key FROM kv_default WHERE (fl_value(body, 'type') = 'task-list') AND (flags & 1) = 0 ORDER BY fl_value(body, 'name')
I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.097ms
E/C4Replicator: statusChangedCallback() handle -> 3409316992, status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
I/LiteCore [SQL]: Compiling JSON query: {"GROUP_BY":[[".taskList.id"]],"WHAT":[[".taskList.id"],["COUNT()",1]],"WHERE":["AND",["=",[".type"],"task"],["=",[".complete"],false]]}
I/LiteCore [SQL]: Compiled Query: SELECT sequence, key, version, flags, fl_value(body, 'taskList.id'), count(1) FROM kv_default WHERE (fl_value(body, 'type') = 'task' AND fl_value(body, 'complete') = 0) AND (flags & 1) = 0 GROUP BY fl_value(body, 'taskList.id')
I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.009ms
I/art: Do full code cache collection, code=120KB, data=100KB
I/art: Starting a blocking GC JitCodeCache
I/art: After code cache collection, code=108KB, data=70KB
I/LiteCoreJNI: [NATIVE] C4Replicator.getResponseHeaders() repl -> 0xcb360c80
E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=4, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
E/Sync: Replicator[<*> blip://172.16.1.234:4985/todo/] is busy, progress 0/0, error: null
E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
E/Sync: Replicator[<*> blip://172.16.1.234:4985/todo/] is stopped, progress 0/0, error: null
I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xcb360c80
I/LiteCore [Actor]: Repl->blip:172.16.1.234:4985/todo/_blipsync performNextMessage
E/EGL_emulation: tid 8601: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcb48b280, error=EGL_BAD_MATCH
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
```

This cluster config

```
[pool]
ma1 ansible_host=172.16.1.177
ma2 ansible_host=172.16.1.234
ma3 ansible_host=172.16.1.68
ma4 ansible_host=172.16.1.98

[couchbase_servers]
cb1 ansible_host=172.16.1.177

[sync_gateways]
sg1 ansible_host=172.16.1.234

[sg_accels]
ac1 ansible_host=172.16.1.68

[load_generators]

[load_balancers]

[webhook_ip]
tf1 ansible_host=172.16.1.227

[environment]
cbs_ssl_enabled=False
xattrs_enabled=True
sg_lb_enabled=False
server_version=5.0.0-3519
sync_gateway_version=1.5.1-4
no_conflicts_enabled=False
```

**Comment by djpongh** [comment]
Dup of https://github.com/couchbase/sync_gateway/issues/3165 ?
