### ISSUE TITLE
Android: ReLogin causes app crash

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/mobile-training-todo#49]
```
11-03 20:43:52.664 5845-5845/com.couchbase.todo E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.couchbase.todo, PID: 5845
   java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
       at com.couchbase.todo.ListsActivity$ListAdapter.getView(ListsActivity.java:219)
       at android.widget.AbsListView.obtainView(AbsListView.java:2362)
       at android.widget.ListView.makeAndAddView(ListView.java:1970)
       at android.widget.ListView.fillDown(ListView.java:704)
       at android.widget.ListView.fillFromTop(ListView.java:765)
       at android.widget.ListView.layoutChildren(ListView.java:1716)
       at android.widget.AbsListView.onLayout(AbsListView.java:2161)
       at android.view.View.layout(View.java:17522)
       at android.view.ViewGroup.layout(ViewGroup.java:5612)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17522)
       at android.view.ViewGroup.layout(ViewGroup.java:5612)
       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1364)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:846)
       at android.view.View.layout(View.java:17522)
       at android.view.ViewGroup.layout(ViewGroup.java:5612)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17522)
       at android.view.ViewGroup.layout(ViewGroup.java:5612)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17522)
       at android.view.ViewGroup.layout(ViewGroup.java:5612)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17522)
       at android.view.ViewGroup.layout(ViewGroup.java:5612)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17522)
       at android.view.ViewGroup.layout(ViewGroup.java:5612)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
       at android.view.View.layout(View.java:17522)
       at android.view.ViewGroup.layout(ViewGroup.java:5612)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2342)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by borrrden** [comment]
I think I have addressed this
